import { v4 as uuid } from 'uuid';
import { convertPptToPdf } from '../services/pptService.js';
import { generatePdf } from '../services/pdfService.js';
import {
  uploadPdf,
  generateSummaryFromPdfs
} from '../services/llmService.js';
import { sendMailWithAttachment } from '../services/mailService.js';
import { saveMetadata, getAllMetadata } from '../utils/fileUtils.js';

import { generateDocx } from '../services/generateDocx.js';



export const generateExecutiveSummary = async (req, res) => {
  try {
    console.log("🚀 Step 0: Request received");

    const prevPpt = req.files.previousWeek[0];
    const currPpt = req.files.currentWeek[0];

    const id = uuid();

    const prevPdf = `src/storage/generated/${id}-prev.pdf`;
    const currPdf = `src/storage/generated/${id}-curr.pdf`;
    const finalPdf = `src/storage/generated/${id}-executive-summary.pdf`;
    const finalDocx = `src/storage/generatedSummary/${id}-executive-summary.docx`;

    await convertPptToPdf(prevPpt.path, prevPdf);
    await convertPptToPdf(currPpt.path, currPdf);

    console.log("✅ PDFs generated");

    //  Upload PDFs to OpenAI
    const prevPdfId = await uploadPdf(prevPdf);
    const currPdfId = await uploadPdf(currPdf);

    console.log("✅ PDFs uploaded to OpenAI");

    //  LLM reads PDFs directly
    const summaryJson = await generateSummaryFromPdfs(prevPdfId, currPdfId, 'file-QtdoRQQ8gReakjxo8sFtrH',);

    console.log("✅ Executive summary generated by LLM");
    console.log("DEBUG: LLM Response Structure:", JSON.stringify(summaryJson, null, 2).substring(0, 500) + "...");

    await generateDocx(summaryJson, finalDocx);


    // await generatePdf(summaryJson, finalPdf);
    await sendMailWithAttachment(finalDocx);

    saveMetadata({
      fileId: id,
      millName: summaryJson.header?.mill_name || "Unknown Mill",
      week: summaryJson.header?.week || "Unknown Week",
      fileName: `${id}-executive-summary.docx`,
      filePath: `reports/download/${id}-executive-summary.docx`,
      createdAt: new Date().toISOString()
    });



    res.json({
      success: true,
      summary: summaryJson,
      fileId: id,
      message: 'Executive summary generated successfully'
    });

  } catch (error) {
    console.error("❌ Error occurred:", error);
    res.status(500).json({ error: error.message });
  }
};

export const getAllReports = async (req, res) => {
  try {
    const reports = getAllMetadata();
    res.json(reports);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

